Código da Equipe: 99
Componentes: Fulano da Silva; fulano.silva@ucsal.edu.br; (71)9999-9999
            Beltrano de Souza; beltrano.souza@ucsal.edu.br; (71)8888-8888
            Ciclano Pereira; ciclano.pereira@ucsal.edu.br; (71)7777-7777

RELATÓRIO DA ANÁLISE LÉXICA. Texto fonte analisado: test.242
----------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------
Lexeme: VAR1, Código: C07, ÍndiceTabSimb: 1, Linha: 1.
----------------------------------------------------------------------------------------
Lexeme: VAR2, Código: C07, ÍndiceTabSimb: 2, Linha: 1.
----------------------------------------------------------------------------------------
Lexeme: VAR3, Código: C07, ÍndiceTabSimb: 3, Linha: 1.
----------------------------------------------------------------------------------------
Lexeme: VAR1, Código: C07, ÍndiceTabSimb: 1, Linha: 2.
----------------------------------------------------------------------------------------
Lexeme: VAR1, Código: C07, ÍndiceTabSimb: 1, Linha: 2.
----------------------------------------------------------------------------------------
Lexeme: VAR1, Código: C07, ÍndiceTabSimb: 1, Linha: 2.
----------------------------------------------------------------------------------------
Lexeme: VAR2, Código: C07, ÍndiceTabSimb: 2, Linha: 3.
----------------------------------------------------------------------------------------
Lexeme: VAR2, Código: C07, ÍndiceTabSimb: 2, Linha: 3.
----------------------------------------------------------------------------------------
Lexeme: VAR1, Código: C07, ÍndiceTabSimb: 1, Linha: 3.
