Relatório da Análise Léxica:
Lexeme: salario, Código: C07, ÍndiceTabSimb: 1, Linha 1
Lexeme: :, Código: B05, ÍndiceTabSimb: -, Linha 1
Lexeme: 5e3, Código: C04, ÍndiceTabSimb: -, Linha 1
Lexeme: ;, Código: B07, ÍndiceTabSimb: -, Linha 1
Lexeme: velocidade, Código: C07, ÍndiceTabSimb: 1, Linha 2
Lexeme: :, Código: B05, ÍndiceTabSimb: -, Linha 2
Lexeme: 1.2e-4, Código: C04, ÍndiceTabSimb: -, Linha 2
Lexeme: ;, Código: B07, ÍndiceTabSimb: -, Linha 2
Lexeme: peso, Código: C07, ÍndiceTabSimb: 2, Linha 3
Lexeme: :, Código: B05, ÍndiceTabSimb: -, Linha 3
Lexeme: 3.45e+2, Código: C04, ÍndiceTabSimb: -, Linha 3
Lexeme: ;, Código: B07, ÍndiceTabSimb: -, Linha 3
Lexeme: distancia, Código: C07, ÍndiceTabSimb: 4, Linha 4
Lexeme: :, Código: B05, ÍndiceTabSimb: -, Linha 4
Lexeme: 100, Código: C03, ÍndiceTabSimb: -, Linha 4
Lexeme: ;, Código: B07, ÍndiceTabSimb: -, Linha 4
