Código da Equipe: 01
Componentes: Arthur de Miranda Xavier; arthur.xavier@ucsal.edu.br; (71)98189-0986
            Kevin Vasques Santos; kevinvasques.santos@ucsal.edu.br; (71)99724-5890
            João Victor Santana Ferreira; joaovictor.ferreira@ucsal.edu.br; (71)99252-6546
            Windson Carlos Pionório Teixeira Filho; windson.filho@ucsal.edu.br; (71)98710-8000


RELATÓRIO DA ANÁLISE LÉXICA. Texto fonte analisado: test.242
----------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------
Lexeme: INTEIRO, Código: A14, ÍndiceTabSimb: -, Linha: 1.
----------------------------------------------------------------------------------------
Lexeme: 123456789123456789123456789123456789123456789, Código: C03, ÍndiceTabSimb: -, Linha: 1.
